In [2]:
import numpy as np
import matplotlib.image as im

image = im.imread('peacock.jpg')
print(type(image))
print(image[0:2,0:2])

<class 'numpy.ndarray'>
[[[92 95 76]
  [91 94 75]]

 [[90 93 76]
  [90 93 76]]]


In [3]:
print(image[0,0,0])


92


In [4]:
#look at the size to decide grey scale or RGB
np.size(image[0,0])

3

In [5]:
imagefname = 'peacock.jpg'

In [6]:
imnewname = imagefname[0:-4]+'_compressed'+imagefname[-4:]
print(imnewname)

peacock_compressed.jpg


In [7]:
imagefname[-2:]

'pg'

In [8]:
image_r = image[:,:,0]
[u_r,s_r,v_r] = np.linalg.svd(image_r)
print(s_r.shape,u_r.shape,v_r.shape)

(663,) (663, 663) (800, 800)


In [9]:
s_r_d = np.diag(s_r)
s_r_d.shape

append = np.zeros((663,800-663))
s_r_cst = np.zeros((663,800))
s_r_cst[:,663:] = append
s_r_cst[:,0:663] = s_r_d

In [10]:
image_cst=u_r.dot(s_r_cst.dot(v_r))

In [11]:
image_cst[50,56]

186.99999999999997

In [12]:
image_r[50,56]

187

In [13]:
#this is enough
image_cst2 = u_r.dot(s_r_d.dot(v_r[0:len(s_r),:]))

In [14]:
image_cst2[50,56]

186.99999999999997

In [15]:
factor = 0.2
newlen = int(len(s_r)*factor)
print(newlen)

132


In [30]:
s_r_d = np.diag(s_r[0:newlen])
image_cp=u_r[:,0:newlen].dot(s_r_d.dot(v_r[0:newlen,:]))

In [31]:
image_cp[50,56]
image_cp= image_cp.astype('uint8')
print(image_cp[50,56],type(image_cp[50,56]))

186.32230037 <class 'numpy.float64'>


In [17]:
array = np.zeros(image_cp.shape)
array.shape

(663, 800)

In [3]:
import im_compress
im_compress.im_compress('peacock.jpg',0.85)